#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xwallpaper --zoom ${XDG_DATA_HOME:-$HOME/.local/share}/северное_сияние.jpg &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
setxkbmap -layout us,ru -option grp:toggle &
xset r rate 300 50

autostart="mpd xcompmgr"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
