#!/bin/sh

# I use startx/xinit like a Chad, so this file will be sourced.

xwallpaper --zoom ${XDG_DATA_HOME:-$HOME/.local/share}/sky.jpg
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
xcompmgr &		# xcompmgr for transparency
slstatus &
xset r rate 300 50	# Speed xrate up
